// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Theo_EnemyHPGauge","status":true,"description":"v1.0.1 - Theo Enemy HP Gauge | Visual HP gauge for the enemies","parameters":{"option":"","pos":"Bottom","defeat":"false","alwaysShown":"true","prop":"","width":"100","height":"11","animeDur":"45","displayDur":"25","border":"2","segments":"1","gaugecolor":"","lcolorindex":"20","rcolorindex":"21","bcolorindex":"15","aftImage":"18","aftAlpha":"200"}}
];
